import type { Workspace } from './types';
import { validateWorkspace } from './domain';

export function createEmptyWorkspace(id: string, name: string): Workspace {
  return validateWorkspace({ id, name, revision: 0, lots: [], batches: [], shipments: [], recalls: [] });
}

/** Entirely synthetic teaching data. No actual businesses, shipments or recalls are represented. */
export function createDemoWorkspace(id = 'workspace-demo'): Workspace {
  return validateWorkspace({
    id,
    name: 'Ember & Oak · demo',
    revision: 0,
    recalls: [],
    lots: [
      {
        id: 'lot-paprika-a',
        code: 'PAP-2409',
        name: 'Smoked paprika',
        supplier: 'Red Earth Spices',
        receivedOn: '2026-09-16',
        expiresOn: '2027-03-16',
        quantity: 10,
        unit: 'kg',
        status: 'hold',
        source: 'Synthetic supplier delivery note RES-0916, line 1. Drill alert references lot PAP-2409.',
      },
      {
        id: 'lot-paprika-b',
        code: 'PAP-2410',
        name: 'Smoked paprika',
        supplier: 'Red Earth Spices',
        receivedOn: '2026-09-17',
        expiresOn: '2027-03-17',
        quantity: 10,
        unit: 'kg',
        status: 'available',
        source: 'Synthetic supplier delivery note RES-0917, line 1; separate supplier lot.',
      },
      {
        id: 'lot-tomato',
        code: 'TOM-1609',
        name: 'Tomato purée',
        supplier: 'Orchard Supply Co.',
        receivedOn: '2026-09-16',
        expiresOn: '2026-12-16',
        quantity: 250,
        unit: 'kg',
        status: 'available',
        source: 'Synthetic receiving sheet OSC-0916, line 2.',
      },
      {
        id: 'lot-oil',
        code: 'OIL-1509',
        name: 'Rapeseed oil',
        supplier: 'Orchard Supply Co.',
        receivedOn: '2026-09-15',
        expiresOn: '2027-06-15',
        quantity: 50,
        unit: 'l',
        status: 'available',
        source: 'Synthetic receiving sheet OSC-0915, line 1. Input quantities are recorded in litres.',
      },
      {
        id: 'lot-vinegar',
        code: 'VIN-1509',
        name: 'Cider vinegar',
        supplier: 'Field & Press',
        receivedOn: '2026-09-15',
        expiresOn: '2027-09-15',
        quantity: 60,
        unit: 'l',
        status: 'available',
        source: 'Synthetic delivery note FP-0915, line 3.',
      },
    ],
    batches: [
      {
        id: 'batch-base',
        code: 'BASE-1809',
        name: 'Smoky mother sauce',
        producedOn: '2026-09-18',
        quantity: 120,
        unit: 'kg',
        inputs: [
          { sourceId: 'lot-paprika-a', quantity: 3 },
          { sourceId: 'lot-tomato', quantity: 110 },
          { sourceId: 'lot-oil', quantity: 5 },
          { sourceId: 'lot-vinegar', quantity: 8 },
        ],
        recordsComplete: true,
        notes:
          'Intermediate bulk sauce. Output is measured after cooking; ingredient litres and kilograms are not added together.',
        source: 'Synthetic production sheet EEO-1809-A, signed line-input checklist.',
      },
      {
        id: 'batch-smoky-1',
        code: 'SMK-1809-A',
        name: 'Smoky tomato · morning run',
        producedOn: '2026-09-18',
        quantity: 180,
        unit: 'units',
        inputs: [{ sourceId: 'batch-base', quantity: 45 }],
        recordsComplete: true,
        notes: '180 jars, 250 g nominal fill. Recorded link to the mother sauce.',
        source: 'Synthetic filling log FILL-1809-A, source kettle BASE-1809.',
      },
      {
        id: 'batch-smoky-2',
        code: 'SMK-1809-B',
        name: 'Smoky tomato · afternoon run',
        producedOn: '2026-09-18',
        quantity: 180,
        unit: 'units',
        inputs: [{ sourceId: 'batch-base', quantity: 45 }],
        recordsComplete: true,
        notes: '180 jars, 250 g nominal fill.',
        source: 'Synthetic filling log FILL-1809-B, source kettle BASE-1809.',
      },
      {
        id: 'batch-smoky-3',
        code: 'SMK-1909-A',
        name: 'Smoky tomato · small run',
        producedOn: '2026-09-19',
        quantity: 120,
        unit: 'units',
        inputs: [{ sourceId: 'batch-base', quantity: 30 }],
        recordsComplete: true,
        notes: '120 jars; completes the recorded allocation of the 120 kg mother sauce.',
        source: 'Synthetic filling log FILL-1909-A, source kettle BASE-1809.',
      },
      {
        id: 'batch-uncertain',
        code: 'CHL-1909-X',
        name: 'Chilli relish · incomplete record',
        producedOn: '2026-09-19',
        quantity: 120,
        unit: 'units',
        inputs: [
          { sourceId: 'lot-tomato', quantity: 25 },
          { sourceId: 'lot-vinegar', quantity: 3 },
        ],
        recordsComplete: false,
        notes:
          'The spice entry is missing from the handwritten production sheet. PAP-2409 cannot be ruled out. Investigate before making a recall decision.',
        source: 'Synthetic production sheet EEO-1909-X; spice lot box left blank.',
      },
      {
        id: 'batch-separate',
        code: 'SMK-2009-A',
        name: 'Smoky tomato · separate lot',
        producedOn: '2026-09-20',
        quantity: 240,
        unit: 'units',
        inputs: [
          { sourceId: 'lot-paprika-b', quantity: 1.5 },
          { sourceId: 'lot-tomato', quantity: 55 },
          { sourceId: 'lot-oil', quantity: 2.5 },
          { sourceId: 'lot-vinegar', quantity: 4 },
        ],
        recordsComplete: true,
        notes:
          'Records name a different paprika lot. No recorded connection to PAP-2409 is not a food-safety clearance.',
        source: 'Synthetic production sheet EEO-2009-A and ingredient-label check.',
      },
    ],
    shipments: [
      {
        id: 'shipment-market',
        code: 'SHP-1909-01',
        batchId: 'batch-smoky-1',
        customer: 'Willow Market',
        contact: 'buyer@willow.example',
        quantity: 120,
        shippedOn: '2026-09-19',
        source: 'Synthetic dispatch note DN-1909-01: 10 cases × 12 jars.',
      },
      {
        id: 'shipment-pantry',
        code: 'SHP-1909-02',
        batchId: 'batch-smoky-2',
        customer: 'Neighbourhood Pantry',
        contact: 'team@pantry.example',
        quantity: 120,
        shippedOn: '2026-09-19',
        source: 'Synthetic dispatch note DN-1909-02: 10 cases × 12 jars.',
      },
      {
        id: 'shipment-table',
        code: 'SHP-2009-01',
        batchId: 'batch-smoky-3',
        customer: 'Sunday Table',
        contact: 'hello@sundaytable.example',
        quantity: 60,
        shippedOn: '2026-09-20',
        source: 'Synthetic dispatch note DN-2009-01: 5 cases × 12 jars.',
      },
      {
        id: 'shipment-uncertain',
        code: 'SHP-2009-02',
        batchId: 'batch-uncertain',
        customer: 'Willow Market',
        contact: 'buyer@willow.example',
        quantity: 48,
        shippedOn: '2026-09-20',
        source: 'Synthetic dispatch note DN-2009-02. Upstream spice entry requires investigation.',
      },
    ],
  });
}
